#define     SWS                         4
#define     RWS                         4
#define     DELIMETER                   ':'
#define     FIRST_ACK                   "ACK$"
#define     PACKET_LOST_THRESHOLD       3
#define     DROP_PROB                   0.1
#define     LOG_DELIM                   "-----------------------------------------------------\n"
#define     FILE_ADDRESS                "../test/francais.txt"
#define     CHUNK_SIZE                  1500
typedef     std::string                 frame;
#define     MAX_BUFFER_SIZE             10
#define     BUFFER_SEND_THRESHOLD       1